app:
  version: 1.0.0
  name: palm-server

email:
  username: finstart.mailer
  password: Shaxz0da201306
  host: mail.molbulak.com
  address: mail.molbulak.com:25

service:
  enabled: false
  description: palm-server
  options:
    Restart: on-success
    SuccessExitStatus: 1 2 8 SIGKILL

fr:
  url: http://46.148.231.73:8091
  developerId: 106567582

actions:
  defaultLang: ru
  apiMethodSystems: mbpayments

server:
  grpcPort: 3001
  port: 3002
  enableCORS: true
  enableThrottleMode: true
  http:
    ssl:
      network: tcp4
      certFile: common/ssl/molbulak.com.crt
      keyFile: common/ssl/molbulak.com.key
      enabled: false
    multipart:
      maxRequestSizeBytes: 5MB

templates:
  optimize: true

java-tools:
  url: http://82.146.41.108:5007

profile: dev

prod:
  mainServiceUrl: http://192.168.200.85:5002

dev:
  mainServiceUrl: http://192.168.200.85:5005

