app:
  version: 1.0.0
  name: palm-server

email:
  username: finstart.mailer
  password: Shaxz0da201306
  host: mail.molbulak.com
  address: mail.molbulak.com:25

service:
  enabled: false
  description: palm-server
  options:
    Restart: on-success
    SuccessExitStatus: 1 2 8 SIGKILL

fr:
  url: http://46.148.231.73:8091
  developerId: 106567582

actions:
  defaultLang: ru
  apiMethodSystems: mbpayments

server:
  IP: localhost
#  url: https://dev-platform.palmautic.ru/api
  grpcPort: 3001
  port: 3002
  enableCORS: true
  enableThrottleMode: true
  http:
    ssl:
      network: tcp4
      certFile: common/ssl/molbulak.com.crt
      keyFile: common/ssl/molbulak.com.key
      enabled: false
    multipart:
      maxRequestSizeBytes: 5MB

templates:
  optimize: true

accounting:
  recoverTariffCron: 0 0 * * *

emailScanner:
  sleepSec: 60

java-tools:
  url: http://172.24.64.1:5008

profile: dev

prod:
  mainServiceUrl: http://82.146.41.108:5008
  db:
    url: root:92559255@tcp(localhost:3306)/palmautic_prod?charset=utf8mb4&allowPublicKeyRetrieval=true&useSSL=false

dev:
  mainServiceUrl: http://172.24.64.1:5008
  db:
    url: myuser3:92559255@tcp(172.27.32.1:3306)/palmautic?charset=utf8mb4&parseTime=True&loc=Local&allowPublicKeyRetrieval=true&useSSL=false

